FROM anapsix/alpine-java
MAINTAINER venkat 
COPY NumberGenerator-1.0.1-SNAPSHOT.jar /var/lib/jenkins/workspace/ECS-job/Docker/NumberGenerator-1.0.1-SNAPSHOT
CMD ["java","-jar","/var/lib/jenkins/workspace/ECS-job/Docker/NumberGenerator-1.0.1-SNAPSHOT.jar"]